import type { RcFile } from "antd/es/upload"; // 或者是原生 File 类型
/**
 * 阿里云 OSS 常见 Content-Type (MIME) 列表
 * 来源: https://help.aliyun.com/zh/oss/user-guide/configure-the-content-type-header
 */
export const OssMimeTypeMap: Record<string, string> = {
	// 默认/未知
	"": "application/octet-stream",
	".*": "application/octet-stream",

	// 常见图片
	".jpg": "image/jpg",
	".jpeg": "image/jpeg",
	".png": "image/png",
	".gif": "image/gif",
	".bmp": "image/bmp",
	".webp": "image/webp",
	".ico": "image/x-icon",
	".svg": "image/svg+xml",
	".tif": "image/tiff",
	".tiff": "image/tiff",

	// 常见文档
	".txt": "text/plain",
	".html": "text/html",
	".htm": "text/html",
	".css": "text/css",
	".js": "application/x-javascript", // 也可以是 text/javascript 或 application/javascript，此处保持阿里云文档一致
	".xml": "text/xml",
	".json": "application/json", // 注意：阿里云列表原文中可能未列出json，但前端常用，建议补上
	".pdf": "application/pdf",
	".doc": "application/msword",
	".docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
	".xls": "application/vnd.ms-excel",
	".xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
	".ppt": "application/vnd.ms-powerpoint",
	".pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",

	// 常见音视频
	".mp3": "audio/mpeg",
	".mp4": "video/mp4",
	".wav": "audio/wav",
	".avi": "video/x-msvideo",
	".mov": "video/quicktime",
	".flv": "video/x-flv", // 补充常见
	".m3u8": "application/x-mpegURL", // 补充常见
	".ts": "video/MP2T", // 补充常见
	".webm": "video/webm", // 补充常见

	// 阿里云文档完整列表提取
	".001": "application/x-001",
	".301": "application/x-301",
	".323": "text/h323",
	".906": "application/x-906",
	".907": "drawing/907",
	".a11": "application/x-a11",
	".acp": "audio/x-mei-aac",
	".ai": "application/postscript",
	".aif": "audio/aiff",
	".aifc": "audio/aiff",
	".aiff": "audio/aiff",
	".anv": "application/x-anv",
	".apk": "application/vnd.android.package-archive",
	".asa": "text/asa",
	".asf": "video/x-ms-asf",
	".asp": "text/asp",
	".asx": "video/x-ms-asf",
	".au": "audio/basic",
	".awf": "application/vnd.adobe.workflow",
	".biz": "text/xml",
	".bot": "application/x-bot",
	".c4t": "application/x-c4t",
	".c90": "application/x-c90",
	".cal": "application/x-cals",
	".cat": "application/vnd.ms-pki.seccat",
	".cdf": "application/x-netcdf",
	".cdr": "application/x-cdr",
	".cel": "application/x-cel",
	".cer": "application/x-x509-ca-cert",
	".cg4": "application/x-g4",
	".cgm": "application/x-cgm",
	".cit": "application/x-cit",
	".class": "java/*",
	".cml": "text/xml",
	".cmp": "application/x-cmp",
	".cmx": "application/x-cmx",
	".cot": "application/x-cot",
	".crl": "application/pkix-crl",
	".crt": "application/x-x509-ca-cert",
	".csi": "application/x-csi",
	".csv": "text/csv",
	".cut": "application/x-cut",
	".dbf": "application/x-dbf",
	".dbm": "application/x-dbm",
	".dbx": "application/x-dbx",
	".dcd": "text/xml",
	".dcx": "application/x-dcx",
	".der": "application/x-x509-ca-cert",
	".dgn": "application/x-dgn",
	".dib": "application/x-dib",
	".dll": "application/x-msdownload",
	".dot": "application/msword",
	".drw": "application/x-drw",
	".dtd": "text/xml",
	".dwf": "application/x-dwf",
	".dwg": "application/x-dwg",
	".dxb": "application/x-dxb",
	".dxf": "application/x-dxf",
	".edn": "application/vnd.adobe.edn",
	".emf": "application/x-emf",
	".eml": "message/rfc822",
	".ent": "text/xml",
	".epi": "application/x-epi",
	".eps": "application/postscript",
	".etd": "application/x-ebx",
	".exe": "application/x-msdownload",
	".fax": "image/fax",
	".fdf": "application/vnd.fdf",
	".fif": "application/fractals",
	".fo": "text/xml",
	".frm": "application/x-frm",
	".g4": "application/x-g4",
	".gbr": "application/x-gbr",
	".gl2": "application/x-gl2",
	".gp4": "application/x-gp4",
	".hgl": "application/x-hgl",
	".hmr": "application/x-hmr",
	".hpg": "application/x-hpgl",
	".hpl": "application/x-hpl",
	".hqx": "application/mac-binhex40",
	".hrf": "application/x-hrf",
	".hta": "application/hta",
	".htc": "text/x-component",
	".htt": "text/webviewhtml",
	".htx": "text/html",
	".icb": "application/x-icb",
	".iff": "application/x-iff",
	".ig4": "application/x-g4",
	".igs": "application/x-igs",
	".iii": "application/x-iphone",
	".img": "application/x-img",
	".ins": "application/x-internet-signup",
	".ipa": "application/vnd.iphone",
	".isp": "application/x-internet-signup",
	".IVF": "video/x-ivf",
	".java": "java/*",
	".jfif": "image/jpeg",
	".jpe": "image/jpeg", // 文档中有两个值，image/jpeg 更通用
	".jsp": "text/html",
	".la1": "audio/x-liquid-file",
	".lar": "application/x-laplayer-reg",
	".latex": "application/x-latex",
	".lavs": "audio/x-liquid-secure",
	".lbm": "application/x-lbm",
	".lmsff": "audio/x-la-lms",
	".ls": "application/x-javascript",
	".ltr": "application/x-ltr",
	".m1v": "video/x-mpeg",
	".m2v": "video/x-mpeg",
	".m3u": "audio/mpegurl",
	".m4e": "video/mpeg4",
	".mac": "application/x-mac",
	".man": "application/x-troff-man",
	".math": "text/xml",
	".mdb": "application/msaccess", // 优先使用 msaccess
	".mfp": "application/x-shockwave-flash",
	".mht": "message/rfc822",
	".mhtml": "message/rfc822",
	".mi": "application/x-mi",
	".mid": "audio/mid",
	".midi": "audio/mid",
	".mil": "application/x-mil",
	".mml": "text/xml",
	".mnd": "audio/x-musicnet-download",
	".mns": "audio/x-musicnet-stream",
	".mocha": "application/x-javascript",
	".movie": "video/x-sgi-movie",
	".mp1": "audio/mp1",
	".mp2": "audio/mp2",
	".mp2v": "video/mpeg",
	".mpa": "video/x-mpg",
	".mpd": "application/vnd.ms-project",
	".mpe": "video/x-mpeg",
	".mpeg": "video/mpg",
	".mpg": "video/mpg",
	".mpga": "audio/rn-mpeg",
	".mpp": "application/vnd.ms-project",
	".mps": "video/x-mpeg",
	".mpt": "application/vnd.ms-project",
	".mpv": "video/mpg",
	".mpv2": "video/mpeg",
	".mpw": "application/vnd.ms-project",
	".mpx": "application/vnd.ms-project",
	".mtx": "text/xml",
	".mxp": "application/x-mmxp",
	".net": "image/pnetvue",
	".nrf": "application/x-nrf",
	".nws": "message/rfc822",
	".odc": "text/x-ms-odc",
	".out": "application/x-out",
	".p10": "application/pkcs10",
	".p12": "application/x-pkcs12",
	".p7b": "application/x-pkcs7-certificates",
	".p7c": "application/pkcs7-mime",
	".p7m": "application/pkcs7-mime",
	".p7r": "application/x-pkcs7-certreqresp",
	".p7s": "application/pkcs7-signature",
	".pc5": "application/x-pc5",
	".pci": "application/x-pci",
	".pcl": "application/x-pcl",
	".pcx": "application/x-pcx",
	".pdb": "chemical/x-pdb",
	".pdx": "application/vnd.adobe.pdx",
	".pfx": "application/x-pkcs12",
	".pgl": "application/x-pgl",
	".pic": "application/x-pic",
	".pko": "application/vnd.ms-pki.pko",
	".pl": "application/x-perl",
	".plg": "text/html",
	".pls": "audio/scpls",
	".plt": "application/x-plt",
	".pot": "application/vnd.ms-powerpoint",
	".potx": "application/vnd.openxmlformats-officedocument.presentationml.template",
	".ppa": "application/vnd.ms-powerpoint",
	".ppm": "application/x-ppm",
	".pps": "application/vnd.ms-powerpoint",
	".ppsx": "application/vnd.openxmlformats-officedocument.presentationml.slideshow",
	".pr": "application/x-pr",
	".prf": "application/pics-rules",
	".prn": "application/x-prn",
	".prt": "application/x-prt",
	".ps": "application/postscript",
	".ptn": "application/x-ptn",
	".pwz": "application/vnd.ms-powerpoint",
	".r3t": "text/vnd.rn-realtext3d",
	".ra": "audio/vnd.rn-realaudio",
	".ram": "audio/x-pn-realaudio",
	".ras": "application/x-ras",
	".rat": "application/rat-file",
	".rdf": "text/xml",
	".rec": "application/vnd.rn-recording",
	".red": "application/x-red",
	".rgb": "application/x-rgb",
	".rjs": "application/vnd.rn-realsystem-rjs",
	".rjt": "application/vnd.rn-realsystem-rjt",
	".rlc": "application/x-rlc",
	".rle": "application/x-rle",
	".rm": "application/vnd.rn-realmedia",
	".rmf": "application/vnd.adobe.rmf",
	".rmi": "audio/mid",
	".rmj": "application/vnd.rn-realsystem-rmj",
	".rmm": "audio/x-pn-realaudio",
	".rmp": "application/vnd.rn-rn_music_package",
	".rms": "application/vnd.rn-realmedia-secure",
	".rmvb": "application/vnd.rn-realmedia-vbr",
	".rmx": "application/vnd.rn-realsystem-rmx",
	".rnx": "application/vnd.rn-realplayer",
	".rp": "image/vnd.rn-realpix",
	".rpm": "audio/x-pn-realaudio-plugin",
	".rsml": "application/vnd.rn-rsml",
	".rt": "text/vnd.rn-realtext",
	".rtf": "application/msword", // 文档也列了 application/x-rtf，msword 更通用
	".rv": "video/vnd.rn-realvideo",
	".sam": "application/x-sam",
	".sat": "application/x-sat",
	".sdp": "application/sdp",
	".sdw": "application/x-sdw",
	".sis": "application/vnd.symbian.install",
	".sisx": "application/vnd.symbian.install",
	".sit": "application/x-stuffit",
	".slb": "application/x-slb",
	".sld": "application/x-sld",
	".sldx": "application/vnd.openxmlformats-officedocument.presentationml.slide",
	".slk": "drawing/x-slk",
	".smi": "application/smil",
	".smil": "application/smil",
	".smk": "application/x-smk",
	".snd": "audio/basic",
	".sol": "text/plain",
	".sor": "text/plain",
	".spc": "application/x-pkcs7-certificates",
	".spl": "application/futuresplash",
	".spp": "text/xml",
	".ssm": "application/streamingmedia",
	".sst": "application/vnd.ms-pki.certstore",
	".stl": "application/vnd.ms-pki.stl",
	".stm": "text/html",
	".sty": "application/x-sty",
	".swf": "application/x-shockwave-flash",
	".tdf": "application/x-tdf",
	".tg4": "application/x-tg4",
	".tga": "application/x-tga",
	".tld": "text/xml",
	".top": "drawing/x-top",
	".torrent": "application/x-bittorrent",
	".tsd": "text/xml",
	".uin": "application/x-icq",
	".uls": "text/iuls",
	".vcf": "text/x-vcard",
	".vda": "application/x-vda",
	".vdx": "application/vnd.visio",
	".vml": "text/xml",
	".vpg": "application/x-vpeg005",
	".vsd": "application/vnd.visio",
	".vss": "application/vnd.visio",
	".vst": "application/vnd.visio",
	".vsw": "application/vnd.visio",
	".vsx": "application/vnd.visio",
	".vtx": "application/vnd.visio",
	".vxml": "text/xml",
	".wax": "audio/x-ms-wax",
	".wb1": "application/x-wb1",
	".wb2": "application/x-wb2",
	".wb3": "application/x-wb3",
	".wbmp": "image/vnd.wap.wbmp",
	".wiz": "application/msword",
	".wk3": "application/x-wk3",
	".wk4": "application/x-wk4",
	".wkq": "application/x-wkq",
	".wks": "application/x-wks",
	".wm": "video/x-ms-wm",
	".wma": "audio/x-ms-wma",
	".wmd": "application/x-ms-wmd",
	".wmf": "application/x-wmf",
	".wml": "text/vnd.wap.wml",
	".wmv": "video/x-ms-wmv",
	".wmx": "video/x-ms-wmx",
	".wmz": "application/x-ms-wmz",
	".wp6": "application/x-wp6",
	".wpd": "application/x-wpd",
	".wpg": "application/x-wpg",
	".wpl": "application/vnd.ms-wpl",
	".wq1": "application/x-wq1",
	".wr1": "application/x-wr1",
	".wri": "application/x-wri",
	".wrk": "application/x-wrk",
	".ws": "application/x-ws",
	".ws2": "application/x-ws",
	".wsc": "text/scriptlet",
	".wsdl": "text/xml",
	".wvx": "video/x-ms-wvx",
	".xap": "application/x-silverlight-app",
	".x_b": "application/x-x_b",
	".xdp": "application/vnd.adobe.xdp",
	".xdr": "text/xml",
	".xfd": "application/vnd.adobe.xfd",
	".xfdf": "application/vnd.adobe.xfdf",
	".xhtml": "text/html",
	// ".xls": "application/vnd.ms-excel",
	".xltx": "application/vnd.openxmlformats-officedocument.spreadsheetml.template",
	".xlw": "application/x-xlw",
	".xpl": "audio/scpls",
	".xq": "text/xml",
	".xql": "text/xml",
	".xquery": "text/xml",
	".xsd": "text/xml",
	".xsl": "text/xml",
	".xslt": "text/xml",
	".xwd": "application/x-xwd",
	".x_t": "application/x-x_t",
	".yaml": "text/vnd.yaml",
	".yml": "text/vnd.yml",
	".tar": "application/x-tar",
	".zip": "application/zip",
};

/**
 * 智能获取文件的 Content-Type
 * 策略：优先通过后缀名查阿里云标准表 -> 其次使用浏览器识别的 type -> 最后默认二进制流
 */
export function getSmartContentType(file: File | RcFile): string {
	// 1. 尝试从文件名获取后缀
	const filename = file.name || "";
	const lastDotIndex = filename.lastIndexOf(".");

	if (lastDotIndex !== -1) {
		const ext = filename.substring(lastDotIndex).toLowerCase();
		// 2. 如果在我们的标准表中找到了，直接返回标准值 (最稳妥)
		if (OssMimeTypeMap[ext]) {
			return OssMimeTypeMap[ext];
		}
	}

	// 3. 如果表中没有（比如罕见格式），则信任浏览器识别的 type
	if (file.type) {
		return file.type;
	}

	// 4. 实在识别不出来，返回默认流
	return "application/octet-stream";
}
